- name: Run Grafana container
  containers.podman.podman_container:
    name: grafana
    image: docker.io/grafana/grafana
    state: started
    restart_policy: always
    network: monitoring_net
    ports:
      - "3000:3000"

